from ultralytics import YOLO
from flask import request, Flask, jsonify
from waitress import serve
from PIL import Image
import requests

app = Flask(__name__)

# تحميل النماذج
teeth_model = YOLO("best.pt")         # نموذج ترقيم الأسنان
caries_model = YOLO("caries_best.pt") # نموذج الأمراض والتسوس

OLLAMA_URL = "http://localhost:11434/api/generate"

@app.route("/")
def root():
    try:
        with open("templates/index.html", "r", encoding="utf-8") as file:
            return file.read()
    except FileNotFoundError:
        return "الصفحة غير موجودة (templates/index.html)", 404


def get_detections(buf):
    image = Image.open(buf)

    # 1. كشف الأسنان
    teeth_results = teeth_model.predict(image, conf=0.35, iou=0.5)[0]
    best_per_class = {}
    for box in teeth_results.boxes:
        x1, y1, x2, y2 = box.xyxy[0].tolist()
        prob = round(box.conf[0].item() * 100, 1)
        class_name = teeth_results.names[int(box.cls[0].item())]
        
        # تخزين الأفضل بناءً على الثقة [x1, y1, x2, y2, class_name, prob]
        if class_name not in best_per_class or prob > best_per_class[class_name][5]:
            best_per_class[class_name] = [x1, y1, x2, y2, class_name, prob]
            
    teeth_boxes = list(best_per_class.values())

    # 2. كشف الأمراض والتسوس
    caries_results = caries_model.predict(image, conf=0.4)[0]
    disease_boxes = []
    for box in caries_results.boxes:
        x1, y1, x2, y2 = box.xyxy[0].tolist()
        prob = round(box.conf[0].item() * 100, 1)
        class_name = caries_results.names[int(box.cls[0].item())]
        disease_boxes.append([x1, y1, x2, y2, class_name, prob])

    return teeth_boxes, disease_boxes


@app.route("/detect", methods=["POST"])
def detect_objects():
    if "image_file" not in request.files:
        return jsonify([])
    file = request.files["image_file"]
    if file.filename == "":
        return jsonify([])
    try:
        teeth_boxes, disease_boxes = get_detections(file.stream)
        return jsonify(teeth_boxes + disease_boxes)
    except Exception as e:
        print("Error in /detect:", e)
        return jsonify([])


@app.route("/generate_report", methods=["POST"])
def generate_report_route():
    if "image_file" not in request.files:
        return jsonify({"error": "no image"}), 400
    file = request.files["image_file"]
    try:
        teeth_boxes, disease_boxes = get_detections(file.stream)
        report_text = generate_report(teeth_boxes, disease_boxes)
        return jsonify({"report": report_text, "findings_count": len(disease_boxes)})
    except Exception as e:
        print("Error in /generate_report:", e)
        return jsonify({"error": str(e)}), 500


def compute_iou_overlap(box_a, box_b):
    """نسبة تقاطع box_b (تسوس) داخل box_a (سن)"""
    ax1, ay1, ax2, ay2 = box_a
    bx1, by1, bx2, by2 = box_b
    ix1, iy1 = max(ax1, bx1), max(ay1, by1)
    ix2, iy2 = min(ax2, bx2), min(ay2, by2)
    if ix2 <= ix1 or iy2 <= iy1:
        return 0.0
    intersection = (ix2 - ix1) * (iy2 - iy1)
    box_b_area = (bx2 - bx1) * (by2 - by1)
    return intersection / box_b_area if box_b_area > 0 else 0.0


def link_findings_to_teeth(teeth_boxes, disease_boxes):
    """ربط التسوس بالسن بناءً على أعلى نسبة تغطية"""
    linked = []
    for d in disease_boxes:
        d_box = d[:4]
        finding_name = d[4]
        confidence = d[5]
        
        best_tooth = None
        best_overlap = 0.0
        
        for t in teeth_boxes:
            t_box = t[:4]
            tooth_name = t[4]
            overlap = compute_iou_overlap(t_box, d_box)
            
            if overlap > best_overlap:
                best_overlap = overlap
                best_tooth = tooth_name

        linked.append({
            "tooth": best_tooth or "Unspecified",
            "finding": finding_name,
            "confidence": confidence,
            "bbox": d_box
        })
    return linked


def generate_report(teeth_boxes, disease_boxes):
    linked = link_findings_to_teeth(teeth_boxes, disease_boxes) or []

    if linked:
        findings_text = "\n".join(
            f"- Tooth {f.get('tooth', 'Unspecified')}: {f.get('finding', 'Finding')} "
            f"(confidence {f.get('confidence', 0)}%)"
            for f in linked
        )
    else:
        findings_text = "No pathological findings detected."

    prompt = f"""You are a dental imaging assistant generating a structured report from AI detection results. You are NOT a licensed dentist and must never present this as a final diagnosis.

Write the report in exactly this structure:

## Introduction
A clear disclaimer: this report is generated by an AI model, may contain errors, and must be reviewed by a licensed dental professional before any treatment decision. This is not a medical diagnosis.

## Findings
For each finding below, write one short paragraph:
- State the tooth number (FDI notation) and the finding type
- Estimate severity (mild / moderate / severe) based on finding type and confidence:
   Deep Caries, Periapical Lesion = severe; Caries, Root Piece = mild-to-moderate;
   Missing teeth, Impacted, Root Canal Treatment = structural/prior treatment, not active decay (no severity needed, describe status instead)
- Suggest a general next step phrased as "should be evaluated by a dentist for X" — never a definitive treatment order
- If applicable, mention approximate depth/extent implied by the finding type (Caries = surface/moderate, Deep Caries = deeper structural involvement)

## Conclusion
A short summary table: Tooth | Finding | Suggested Action

Detection data:
{findings_text}
"""

    try:
        # الربط المباشر مع Ollama المحلي
        response = requests.post(
            OLLAMA_URL, 
            json={
                "model": "qwen2.5:3b-instruct-q4_K_M",
                "prompt": prompt,
                "stream": False
            }, 
            timeout=120
        )
        response.raise_for_status()
        return response.json().get("response", "تعذر توليد التقرير")
    
    except Exception as e:
        print(f"Ollama Connection Error: {e}")
        return "تعذر توليد التقرير"


if __name__ == "__main__":
    print("Server starting at http://127.0.0.1:8080")
    serve(app, host="127.0.0.1", port=8080)